# Generated by Django 3.2 on 2021-05-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_like_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
