# Generated by Django 3.2 on 2021-05-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timestamp']},
        ),
    ]
